config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books do
    member do
      get 'read'
    end
  end

  devise_for :users, skip: [:passwords, :sessions, :registrations]

    devise_scope :user do
      get 'users/sign_up', to: 'devise/registrations#new', as: :new_user_registration
      post 'users', to: 'devise/registrations#create', as: :user_registration
      get 'users/sign_in', to: 'devise/sessions#new', as: :new_user_session
      post 'users/sign_in', to: 'devise/sessions#create', as: :user_session
      delete 'users/sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  update_index('books') { self }

  has_one_attached :cover, dependent: :destroy
  has_one_attached :content, dependent: :destroy

  validates :title, presence: true, length: { in: 1..150 }
  validates :author, presence: true, length: { in: 1..50 }
  validates :isbn, presence: true, uniqueness: true, format: { with: /\A\d[\d-]*\d\z/ }
  validates :description, length: { maximum: 1000 }
  validates :cover, content_type: [:png, :jpg, :jpeg]
  validates :content, content_type: [:pdf]

  scope :ordered, -> { order(:title) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }
  validates :username, presence: true, uniqueness: true
  validates :firstname, presence: true
  validates :lastname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :firstname, :lastname, :email, :password])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = collection
  end

  def show
    @book = resource
  end

  def new
    @book = Book.new
  end

  def read
    @book = resource
  end

  def edit
    @book = resource
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to book_path(@book), notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @book = resource

    if @book.update(book_params)
      redirect_to book_path(@book), notice: "Book was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    resource.destroy

    redirect_to books_path, notice: 'Book was successfully destroyed.',
      status: :see_other
  end

  private

    def book_params
      params.require(:book).permit(:title, :author, :isbn, :description, :cover, :content)
    end

    def collection
      Book.ordered
    end

    def resource
      collection.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="p-8 rounded-lg bg-slate-100 dark:bg-gray-800">
  <%= image_tag book.cover, class: "h-64" if book.cover.attached? %>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Title:</strong>
    <%= book.title %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Author:</strong>
    <%= book.author %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Isbn:</strong>
    <%= book.isbn %>
  </p>

  <p class="my-5">
    <strong class="block mb-1 font-medium">Description:</strong>
    <%= book.description.truncate(150) %>
  </p>

  <%= link_to "Show this book", book, class: "btn btn-primary" %>
</div>

app/views/books/_form.html.erb
<div class="my-5">
  <%= simple_form_for book, url: polymorphic_path(book), defaults: { input_html: { class: "form" } } do |f| %>
    <div class="my-5">
      <%= f.input :title %>
    </div>
    <div class="my-5">
      <%= f.input :author %>
    </div>
    <div class="my-5">
      <%= f.input :isbn, placeholder: '0000000000000 - 13 digits' %>
    </div>
    <div class="my-5">
      <%= f.input :description %>
     </div>
     <div class="my-5">
      <%= f.input :cover, as: :file %>
     </div>
     <div class="my-5">
      <%= f.input :content, as: :file %>
     </div>
    <div class="my-5">
      <%= f.button :submit, class: "btn btn-green" %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">Editing book</h1>

  <%= render "books/form", book: @book %>

  <%= button_to "Destroy this book", book_path(@book), method: :delete, class: "btn btn-red" %>
  <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
</div>

app/views/books/index.html.erb
<div class="w-full">
  <div class="flex items-center justify-between mb-8">
    <h1 class="text-4xl font-bold">Books</h1>
    <%= link_to "New book", new_book_path, class: "btn btn-green" %>
  </div>

  <div id="books" class="grid grid-cols-3 gap-10">
    <%= render partial: "books/book", collection: @books %>
  </div>
</div>

app/views/books/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold">New book</h1>

  <%= render "books/form", book: @book %>

  <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
</div>

app/views/books/read.html.erb
<div>
  <div>
    <p class="my-5 text-4xl font-bold">
      <%= @book.title %>
    </p>
    <%= link_to "Back to book", book_path(@book), class: "btn btn-primary" %>
  </div>
  <br>
  <div>
    <% if user_signed_in? && @book.content.attached? %>
      <div id="pdf" style="height: 1000px;"></div>
      <div data-controller="pdf"
        data-pdf-url="<%= rails_blob_path(@book.content, only_path: true) %>"
        data-pdf-filename="<%= @book.content.filename %>">
      </div>
      <script src="https://acrobatservices.adobe.com/view-sdk/viewer.js"></script>
      <% else %>
        <strong>Please <%= link_to "sign in", new_user_session_path,  style: "color: blue;" %> to read this book!</strong>
      <% end %>
  </div>
</div>

app/views/books/show.html.erb
<div class="flex w-full mx-auto md:w-2/3">
  <div class="mx-auto">
    <p class="my-5 text-4xl font-bold">
      <%= @book.title %>
    </p>

    <%= image_tag @book.cover, class: "h-2/5" if @book.cover.attached? %>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Author:</strong>
      <%= @book.author %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Isbn:</strong>
      <%= @book.isbn %>
    </p>

    <p class="my-5">
      <strong class="block mb-1 font-medium">Description:</strong>
      <%= @book.description %>
    </p>

    <% if user_signed_in? && @book.content.attached? %>
      <%= link_to "Read this book", read_book_path(@book), class: "btn btn-green" %>
    <% end %>
    <%= link_to "Edit this book", edit_book_path(@book), class: "btn btn-primary" %>
    <%= link_to "Back to books", books_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="flash-<%= type %>">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookReaderApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <main>
      <div class="flash">
      <%= render 'layouts/flash' %>
      </div>
      <div class="container px-5 mx-auto mt-12 mb-24">
        <%= yield %>
      </div>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer
  class="fixed bottom-0 left-0 z-20 w-full text-center bg-neutral-200 dark:bg-neutral-700 lg:text-left">
  <div class="p-4 text-center text-neutral-700 dark:text-neutral-200">
    © <%= Date.today.year %> Copyright
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="sticky top-0 flex flex-wrap items-center px-4 py-4 bg-neutral-200 dark:bg-neutral-700 lg:px-16">
  <div class="flex items-center justify-between flex-1">
    <p><strong>Book Reader</strong></ap>
  </div>

  <div class="hidden w-full h-8 md:flex md:items-center md:w-auto" id="menu">
    <nav>
      <ul class="items-center justify-between pt-4 text-base text-gray-700 md:flex md:pt-0">
      <li> <div class="mx-10 ">
      <%= simple_form_for :search, url: search_books_path, method: :get, html: {  class: "flex items-center search-form", role: "search" } do |f| %>
        <%= f.input :query, as: :search, input_html: { class: "mt-3 border-teal-500", placeholder: "Search book..." }, label: false %>
        <%= f.submit "Search", class: "sign-button mx-4" %>
      <% end %>
    </div></li>
        <li><%= link_to "Books", books_path, class: "block px-0 py-3 md:p-4"%></li>
        <% if user_signed_in? %>
          <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "block px-0 py-3 md:p-4"%></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "block px-0 py-3 md:p-4"%></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "block px-0 py-3 md:p-4"%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>